#! /bin/bash

if [ $# -ne 1 ]; then
    echo  usage: $0 "<path-of-installation-folder>"
    exit 1
fi

INSTALL_FOLDER=$1

for module in `find . -maxdepth 1 -type d -regextype egrep -regex "./gvirtus(\.[a-zA-Z]*|\b)" | sort`
do
  cd $module
  bash install.sh ${INSTALL_FOLDER}
  cd $OLDPWD
done

cd ${INSTALL_FOLDER}/lib/frontend
ln -sf libcurand.so libcurand.so.6.5
ln -sf libcudart.so libcudart.so.9.0
ln -sf libcuda.so libcuda.so.9.0
ln -sf libcublas.so libcublas.so.9.0
ln -sf libcufft.so libcufft.so.9.0

echo
/bin/echo -e "\e[1;97;42;5mINSTALLATION COMPLETED!\e[0m"
echo
echo
